version: '3.8'

services:
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - EVENT_SERVICE_URL=redis://redis:6379/1

  redis:
    image: "redis:7.0-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  static_value:
  media_value:
  redis-data: