# Generated by Django 4.2.11 on 2025-05-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('pred_module', models.CharField(max_length=255)),
                ('pred_func', models.CharField(max_length=255)),
                ('morph_module', models.CharField(max_length=255)),
                ('morph_func', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_terminal', models.BooleanField(default=False)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comwpc.graph')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comwpc.edge')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comwpc.graph')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='comwpc.state')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='comwpc.state')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
