# Generated by Django 4.2.11 on 2026-03-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comwpc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="is_subgraph",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="graph",
            name="parent_graph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subgraphs",
                to="comwpc.graph",
            ),
        ),
        migrations.AddField(
            model_name="graph",
            name="raw_dot",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="array_keys_mapping",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="state",
            name="subgraph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_states",
                to="comwpc.graph",
            ),
        ),
    ]
