# Generated by Django 4.2.11 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comwpc", "0002_graph_is_subgraph_graph_parent_graph_graph_raw_dot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="is_subgraph_node",
            field=models.BooleanField(default=False),
        ),
    ]
