# Generated by Django 4.2.11 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comwpc", "0003_state_is_subgraph_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graph",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="graph",
            constraint=models.UniqueConstraint(
                fields=("name", "is_subgraph"),
                name="unique_graph_name_per_type",
            ),
        ),
    ]
