# Generated by Django 4.2.11 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comwpc", "0004_alter_graph_name_graph_unique_graph_name_per_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="raw_aini",
            field=models.TextField(blank=True, null=True),
        ),
    ]
